export const CHISME_POSTED = 'CHISME_POSTED';
export const CHISME_DELETED = 'CHISME_DELETED';
export const CHISME_CONFIRMED = 'CHISME_CONFIRMED';
export const CHISME_DESCRIBED = 'CHISME_DESCRIBED';
export const CHISME_RECEIVED = 'CHISME_RECEIVED';